apiVersion: apps/v1
kind: Deployment
metadata:
  name: foods-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foods
  template:
    metadata:
      labels:
        app: foods
    spec:
      containers:
        - name: foods
          image: ayzeysdev/foods
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-srv:4222'
            - name: NATS_CLUSTER_ID
              value: ayzeys
            - name: MONGO_URI
              value: 'mongodb://foods-mongo-srv:27017/foods'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: foods-srv
spec:
  selector:
    app: foods
  ports:
    - name: foods
      protocol: TCP
      port: 3000
      targetPort: 3000
